mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appinfodb?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp